sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
cache:
  directories: node_modules
before_script:
  - npm install -g codecov
script:
  - npm run lint
  - npm run flow
  - npm test:coverage
  - codecov
  - npm run build
